# Generated by Django 2.2.8 on 2019-12-09 21:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_artcomments_articledetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='artComments',
            new_name='ArticleComments',
        ),
    ]
